"""Render the agent-facing `context/index.md` from the manifest.

Per `docs-specs/context-seeding.md`, agents discover what's in the
workspace by reading `context/index.md` first. This module is the
sole writer of that file; it's regenerated by the conductor every
time the manifest changes (after add / remove / refresh).

The rendered file is purely derived state — never edited by hand.
"""

from __future__ import annotations

from pathlib import Path

from .manifest import CONTEXT_DIR, ContextEntry, ContextManifest

INDEX_FILENAME = "index.md"


def index_path(workspace: Path) -> Path:
    return workspace / CONTEXT_DIR / INDEX_FILENAME


def render_index(workspace: Path, manifest: ContextManifest) -> None:
    """Regenerate `context/index.md` from the current manifest.

    Creates the parent directory on demand. Writes nothing if the
    manifest is empty (we still create the file — agents need to
    know context is empty rather than guess).
    """
    p = index_path(workspace)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_render(manifest), encoding="utf-8")


# ---------------------------------------------------------------------- #
# Internals
# ---------------------------------------------------------------------- #


def _render(manifest: ContextManifest) -> str:
    if not manifest.entries:
        return _empty_index()

    repos = [e for e in manifest.entries if e.kind == "repo"]
    docs = [e for e in manifest.entries if e.kind == "doc"]
    notes = [e for e in manifest.entries if e.kind == "note"]

    lines: list[str] = [
        "# Context",
        "",
        "Auto-generated by the conductor — read this for an overview of",
        "what's available, then deep-dive by reading any of the linked",
        "files. **Do not edit by hand**; changes are rebuilt from",
        "`context-manifest.yaml` whenever the manifest changes.",
        "",
    ]

    if repos:
        lines.append("## Repos")
        lines.append("")
        for r in repos:
            lines.extend(_render_repo(r))
            lines.append("")

    if docs:
        lines.append("## Docs")
        lines.append("")
        for d in docs:
            lines.extend(_render_doc(d))
            lines.append("")

    if notes:
        lines.append("## Notes")
        lines.append("")
        for n in notes:
            lines.extend(_render_note(n))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_repo(e: ContextEntry) -> list[str]:
    bullet = f"- **{e.name}**"
    if e.source:
        bullet += f" (`{e.source}`)"
    out = [bullet]
    if e.digest_summary:
        out.append(f"  - {e.digest_summary}")
    out.append(f"  - digest: `context/repos/{_slug(e)}/digest.md`")
    out.append(f"  - live tree: `context/repos/{_slug(e)}/source/`")
    if e.digest_status and e.digest_status != "ready":
        out.append(f"  - status: `{e.digest_status}`")
    if e.stale:
        out.append("  - **stale** — source has new commits since last digest")
    return out


def _render_doc(e: ContextEntry) -> list[str]:
    from .operations import doc_filename  # local import — avoid cycle

    bullet = f"- **{e.name}**"
    if e.source:
        bullet += f" (source: `{e.source}`)"
    return [bullet, f"  - file: `context/docs/{doc_filename(e.name)}`"]


def _render_note(e: ContextEntry) -> list[str]:
    return [
        f"- **{e.name}** (added {_format_when(e)})",
        f"  - file: `context/notes/{_slug(e)}.md`",
    ]


def _slug(e: ContextEntry) -> str:
    """Mirror `operations._slugify` — kept here because the index has
    to know the on-disk filename without depending on the operations
    module (avoids a circular import)."""
    from .operations import slugify  # local import — only touched on render

    return slugify(e.name)


def _format_when(e: ContextEntry) -> str:
    return e.added_at.date().isoformat()


def _empty_index() -> str:
    return (
        "# Context\n"
        "\n"
        "No context configured for this workspace yet. The user can add\n"
        "repos, docs, or notes via `quorum context add <path>` or via\n"
        "the Context dialog in the UI.\n"
    )
