"""File-system scaffolding for `quorum init`.

Writes the initial set of files a brand-new workspace needs. Idempotent:
re-running `init` over an existing workspace will fail loudly rather than
overwrite content.
"""

from __future__ import annotations

import shutil
from importlib.resources import files
from pathlib import Path

from ..paths import WorkspacePaths

# ----------------------------------------------------------------------- #
# Top-level file contents
# ----------------------------------------------------------------------- #

PROBLEM_STATEMENT_TEMPLATE = """\
# Problem Statement

<!--
  Fill this in before running `quorum start`. The conductor refuses to
  start with the placeholder content below intact. Sections are guidance,
  not strict — but each one is worth filling in.
-->

## What I'm trying to figure out

<one sentence: the actual question>

## What I already know / believe

<bulleted list of things you're treating as input>

## What I'm uncertain about

<bulleted list of the things this workspace should resolve>

## What "done" looks like

<one paragraph: what artifacts you'd expect to see when this is decided>

## Constraints / non-goals

<things that are explicitly out of scope>

## Existing materials

<links, files, repos already worth pointing the agents at>
"""


CONFIG_YAML_TEMPLATE = """\
schema_version: 0.1

# Routing overrides — Layer 2 of the routing model (design doc §3.6).
# Any role listed here pins to a specific handle workspace-wide.
# Leave empty to use the fitness-based defaults in
# registers/routing-defaults.yaml.
routing:
  overrides: {}

# Per-workspace cost ceiling. Conductor pauses the workspace when spend
# crosses `usd`. Default ON; see Phase 4i. Edit only with intent.
cost:
  ceiling_usd: 50.0
  enforce: true

# Invocation caps. Defaults match design doc §10. Tune as appropriate.
caps:
  per_deliberation_invocations: 20
  no_progress_steps: 6

# Unavailability policy (design doc §10.3): strict | substitute.
# `strict`  - block on the routed handle being unavailable
# `substitute` - fall back to the next-best fitness-rated handle
unavailability_policy: substitute

# Human-timeout policy (design doc §10.4). `auto_deputy_after` may be
# `null` to disable deputy decisions entirely.
human_timeout:
  auto_deputy_after: 30m
  deputy_max_stakes: tactical
"""


PARTICIPANTS_TEMPLATE_HEAD = """\
---
schema_version: 0.1
last_updated: 2026-04-28
---

# Participants Registry

<!--
  Operational registry — the conductor reads this to discover who can do
  what. See design doc §3.5 for full field semantics. Edit by hand for
  v1; a structured editor lives in the UI in Phase 9.
-->

| Handle | Display Name | CLI Command | Model | Transport | Quota (daily/per-deliberation) | Permission Capability | Account Label | Health |
|---|---|---|---|---|---|---|---|---|
"""

PARTICIPANTS_HUMAN_ROW = (
    "| {handle} | You | (manual) | n/a | manual | unlimited | n/a | (none) | n/a |\n"
)


GITIGNORE_TEMPLATE = """\
# Quorum runtime — ephemeral, regenerated by the conductor on each start.
# Never commit. See design doc §7.
runtime/
"""


OUTCOME_MANIFEST_PLACEHOLDER = """\
---
status: DRAFTING
protocol_version: 0.1
created: ""
locked_at: null
template_used: null
---

# Outcome Manifest

<!--
  This file is populated by deliberation #0001 (the bootstrapper). Until
  then, it stays in DRAFTING. Do not hand-edit before that deliberation
  has run; let the protocol produce it.
-->
"""


# ----------------------------------------------------------------------- #
# Routing-defaults discovery
# ----------------------------------------------------------------------- #


def _find_repo_root() -> Path | None:
    """Walk upward from this file to the repo root.

    During development the conductor lives at
    `<repo>/conductor/src/quorum_conductor/`; the protocol, prompts, and
    routing-defaults sit at `<repo>/protocol/`, `<repo>/prompts/`,
    `<repo>/routing-defaults/`. We locate the repo by looking for
    `routing-defaults/routing-defaults.yaml`, which is unique to this
    project's layout.
    """
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "routing-defaults" / "routing-defaults.yaml").is_file():
            return parent
    return None


def _bundled_routing_defaults() -> Path | None:
    repo = _find_repo_root()
    if repo is not None:
        return repo / "routing-defaults" / "routing-defaults.yaml"
    # Packaged fallback (filled in if/when we ship via PyPI).
    try:
        resource = files("quorum_conductor").joinpath("_resources/routing-defaults.yaml")
        if resource.is_file():
            return Path(str(resource))
    except (FileNotFoundError, ModuleNotFoundError):
        pass
    return None


def _bundled_standing_prompt() -> Path | None:
    repo = _find_repo_root()
    if repo is not None:
        return repo / "prompts" / "agent-standing-prompt.md"
    return None


def _bundled_protocol_dir() -> Path | None:
    repo = _find_repo_root()
    if repo is not None:
        return repo / "protocol"
    return None


# ----------------------------------------------------------------------- #
# Public API
# ----------------------------------------------------------------------- #


class ScaffoldingError(RuntimeError):
    """Raised when scaffolding cannot proceed (e.g., target already exists)."""


def scaffold_workspace(
    paths: WorkspacePaths, *, human_handle: str | None = None
) -> None:
    """Create the directory tree and write initial files.

    Refuses to run if `state.yaml` already exists at the target.
    `human_handle` defaults to `identity.default_human_handle()` —
    detected from $USER / git config / fallback. The chosen handle
    becomes the row in `participants.md` and the inbox file name.
    """
    if paths.state_yaml.exists():
        raise ScaffoldingError(
            f"Refusing to scaffold: {paths.state_yaml} already exists. "
            "This directory is already a Quorum workspace."
        )

    if human_handle is None:
        from .identity import default_human_handle

        human_handle = default_human_handle()

    paths.root.mkdir(parents=True, exist_ok=True)
    for d in paths.all_directories():
        d.mkdir(parents=True, exist_ok=True)

    # Top-level files.
    _write_if_missing(paths.problem_statement, PROBLEM_STATEMENT_TEMPLATE)
    _write_if_missing(paths.config_yaml, CONFIG_YAML_TEMPLATE)
    _write_if_missing(paths.outcome_manifest, OUTCOME_MANIFEST_PLACEHOLDER)
    _write_if_missing(paths.gitignore, GITIGNORE_TEMPLATE)

    # Registers.
    participants_body = PARTICIPANTS_TEMPLATE_HEAD + PARTICIPANTS_HUMAN_ROW.format(
        handle=human_handle
    )
    _write_if_missing(paths.participants, participants_body)
    _copy_routing_defaults(paths.routing_defaults)

    # Prompts and protocol — agents need these in-workspace per design-doc §7.
    _copy_standing_prompt(paths.agent_standing_prompt)
    _copy_protocol_dir(paths.protocol)

    # Inbox seed for the human (other handles' inboxes are created lazily).
    _write_if_missing(paths.inbox / f"{human_handle}.md", "")

    # `runtime/` is gitignored by the workspace .gitignore above, but we
    # also drop a directory-level marker so it's clear what's happening.
    _write_if_missing(
        paths.runtime / ".gitignore",
        "# Everything in this directory is ephemeral and managed by the conductor.\n*\n!.gitignore\n",
    )


def _write_if_missing(path: Path, content: str) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _copy_routing_defaults(target: Path) -> None:
    src = _bundled_routing_defaults()
    if src is None:
        # Best-effort fallback: write a stub so the workspace is at least
        # parseable. The user is told to run `quorum refresh-defaults`
        # once we ship that command.
        target.write_text(
            "schema_version: 0.1\n"
            "# Routing defaults could not be located at init time.\n"
            "# Run `quorum refresh-defaults` once that command lands, or\n"
            "# copy the canonical file from the Quorum repo's\n"
            "# routing-defaults/ directory.\n"
            "fitness: {}\ncost: {}\n",
            encoding="utf-8",
        )
        return
    if target.exists():
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, target)


def _copy_standing_prompt(target: Path) -> None:
    if target.exists():
        return
    src = _bundled_standing_prompt()
    target.parent.mkdir(parents=True, exist_ok=True)
    if src is None:
        target.write_text(
            "# Quorum Standing Agent Prompt\n\n"
            "Standing prompt could not be located at init time. Copy it from\n"
            "the Quorum repo's prompts/agent-standing-prompt.md before running\n"
            "`quorum start`.\n",
            encoding="utf-8",
        )
        return
    shutil.copyfile(src, target)


def _copy_protocol_dir(target: Path) -> None:
    """Copy `protocol/PROTOCOL.md` and `protocol/templates/` into the workspace.

    Idempotent: only files that don't already exist at the target are
    written. The `manifest-templates/` directory is not copied — those
    templates are read from the bundled location at init time when a
    user picks one, not stored per-workspace.
    """
    src = _bundled_protocol_dir()
    if src is None:
        return
    target.mkdir(parents=True, exist_ok=True)
    src_md = src / "PROTOCOL.md"
    if src_md.is_file() and not (target / "PROTOCOL.md").exists():
        shutil.copyfile(src_md, target / "PROTOCOL.md")
    for sub in ("templates", "manifest-templates"):
        src_sub = src / sub
        if not src_sub.is_dir():
            continue
        dst_sub = target / sub
        dst_sub.mkdir(parents=True, exist_ok=True)
        for entry in src_sub.iterdir():
            if entry.is_file():
                dst = dst_sub / entry.name
                if not dst.exists():
                    shutil.copyfile(entry, dst)
